### ISSUE TITLE
ERROR: Decryption failed

### ISSUE THREAD

**Issue by caseyrudge** [ozone-development/ozp-ansible#19]
Trying the ozp-quickstart no-frills get it up and running routine.

issued the vagrant up command.  While "default: Running ansible-playbook..." command I get the error: 

ERROR:Decryption failed 
Ansible failed to complete successfully. Any error output should be visible above.  Please fix these errors and try again.

This happens after the machine boots, checks for guest additions, mounts shared folders, runs Ansible and runs the ansible-playbook.

**Comment by clarkjefcoat** [comment]
That error looks like you haven't run this command yet:
`mv group_vars/all/vault_unencrypted.yml group_vars/all/vault.yml`

If you ran it once and then pulled down an updated version of ozp-ansible, you may need to run it again.

**Comment by caseyrudge** [comment]
I went into the group_vars/all directory and it looked like I completed the mv command successfully.  The current  vault.yml file is the one that says vault_jenkins_username: "none" ...

Nonetheless I pulled another clean build and re-ran the quick start instructions.  Looks like the up command worked, nothing different from what was  tried before.
